version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: aws/deploy/scripts/pull_image_dockerhub.sh
      runas: ec2-user
  AfterInstall:
    - location: aws/deploy/scripts/kill_container.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: aws/deploy/scripts/run_container.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: aws/deploy/scripts/clean-up.sh
      timeout: 20
      runas: ec2-user
  
    